version: '3.9'

services:
  tambola-app:
    build: 
      context: ./tambola-game
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./tambola-game:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    restart: always
