version: '3.9'

services:
  frontend:
    build:
      context: ./tambola-game
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: fastapi-backend
    ports:
      - "4000:4000"
    restart: always
